### ISSUE TITLE
[albums] The menu is not in "compact mode" when you view the Batch Manager

### ISSUE THREAD

**Issue by plegall** [mistic100/Piwigo#159]
**Reported by Rio on 6 Apr 2011 17:15**

In administration, the left menu is not in &quot;compact mode&quot; when you view the Batch Manager.
This happens only if you are logged in Italian (Tested on EN, FR, IT)
I&#039;ll update if I find an other example.

**Steps to reproduce:** Login and change language on IT if necessary.
In administration (Amministrazione) go to Photos (Foto) and atch Manager. (Gestione dei lotti)

[Piwigo Bugtracker #2252](http://piwigo.org/bugs/view.php?id=2252)

**Comment by plegall** [comment]
Problem has been fixed, it was due to javascript error with IT language.

**Comment by mistic100** [comment]
**Comment posted by mistic100 on 7 Apr 2011 13:33**

Firebug says &quot;uncaught exception: Huh ?! Line 0&quot;
not very explicit...

**Comment by plegall** [comment]
**Comment posted by Rio on 25 Dec 2011 18:52**

Hi,
Same problem discovered in plugin &quot;Whois Online&quot; tab &quot;Radar Report&quot;
Tested and reproducible with IT, FR and EN languages
